name: Build and publish Docker images

on:
  push:
    branches: [contentful-demo]

jobs:
  publish_k8s_demo:
    runs-on: ubuntu-latest

    env:
      CI: true
      NODE_OPTIONS: --max-old-space-size=4096

    steps:
      - uses: actions/checkout@v2

      - name: Docker Login
        run: docker login --username ${{ secrets.DOCKER_HUB_USERNAME }} --password ${{ secrets.DOCKER_HUB_ACCESS_TOKEN }}

      - name: fetch branch contentful-demo
        run: git fetch origin contentful-demo

      - name: yarn install
        run: yarn install --frozen-lockfile

      - name: type checking and declarations
        run: yarn run tsc --incremental false

      - name: build all packages - TS to JS
        run: yarn run build

      - name: Set image version
        run: echo '::set-env name=IMAGE_VERSION::$(cat IMAGE_VERSION)'

      - name: docker build frontend
        run: yarn run docker-build:app

      - name: docker tag frontend
        run: docker tag spotify/backstage:latest roadiehq/contentful-demo-frontend:${{ env.IMAGE_VERSION }}

      - name: docker push frontend
        run: docker push roadiehq/contentful-demo-frontend:${{ env.IMAGE_VERSION }}

      - name: docker build backend
        run: yarn workspace example-backend build-image

      - name: docker tag backend
        run: docker tag example-backend:latest roadiehq/contentful-demo-backend:${{ env.IMAGE_VERSION }}

      - name: docker push backend
        run: docker push roadiehq/contentful-demo-backend:${{ env.IMAGE_VERSION }}
